stages:
    - test
newman_tests:
    stage: test
    image:
        name: postman/newman_alpine33
        entrypoint: [""]
    script:
        - newman --version
        - newman run ./collections/restful_api_testing.postman_collection.json -e ./envrionments/restful_api_testing.postman_environment.json --reporters cli,htmlextra --reporter-htmlextra-export testReport.html
    artifacts:
        when: always
        paths:
            - testReport.html